[mnist]
n_tr = 256
n_val = 256
n_test = 256
input_shape = [28, 28, 1]

[emnist]
n_tr = 256
n_val = 256
n_test = 256
input_shape = [28, 28, 1]

[cifar]
n_tr = 256
n_val = 256
n_test = 256
input_shape = [32, 32, 3]

[adult]
n_tr = 256
n_val = 256
n_test = 256
num_features = 100
